# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-06-23 09:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0003_questionmanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuestionManager',
        ),
    ]
